### ISSUE TITLE
Merge application and confirmation view

### ISSUE THREAD

**Issue by xTEddie** [techx/quill#14]
I believe both views should be merged because there was high percentage of bounce rate using this system. This would reduce the number of steps for users to attend the event.

**Comment by jlin816** [comment]
Hi Edward -- thanks for submitting some issues! :) 

Can you clarify what you mean by "bounce rate"? In our experience, we (and other hackathons) separate the application/confirmation stages because there are certain types of information that don't matter for people who aren't attending the event and don't help organizers with the initial admissions / application reading stage -- namely, t-shirt size, dietary restrictions, waiver forms, or topic track preferences. We'd also need applicants to confirm that they're accepting their invitation anyways, so the additional step seems necessary to me. 

Correct me if I'm misunderstanding what you mean!

**Comment by xTEddie** [comment]
Bounce rate is the percentage of visitors who leave after viewing only one page. So we ended up having people not filling the application which is not something we want. 

I clearly understand what you said. I am having a second thoughts right now. In the end, it is not possible to have everything. Maybe there is a better solution to fix this.

**Comment by jlin816** [comment]
Hmm, I see. I think having more questions on the initial application side would increase friction. If you push these questions to a confirmation step, after hackers have already been admitted, it seems like they would be more likely to put in the work to answer them -- and if they don't even do the few questions we need to confirm their attendance, then I'm not sure they'd even go through the trouble of going to the hackathon at all.  Perhaps this is more of an organizing issue than a software one -- closing this issue for now.
